package db

import (
	"strings"
	"time"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// GroupChatMessage keeps a short-lived, group-scoped copy of chat text for
// local-only word clouds and activity rankings. Callers periodically delete
// rows outside the retention window.
type GroupChatMessage struct {
	ID           uint   `gorm:"primarykey;autoIncrement"`
	GroupID      int64  `gorm:"not null;uniqueIndex:idx_group_chat_message;index:idx_group_chat_time,priority:1;index:idx_group_chat_user_time,priority:1"`
	MessageID    int32  `gorm:"not null;uniqueIndex:idx_group_chat_message"`
	UserID       int64  `gorm:"not null;index:idx_group_chat_user_time,priority:2"`
	Nickname     string `gorm:"size:64"`
	Content      string `gorm:"type:text"`
	StatExcluded bool   `gorm:"not null;default:false"`
	CreatedAt    int64  `gorm:"not null;index:idx_group_chat_time,priority:2;index:idx_group_chat_user_time,priority:3"`
}

type GroupChatSummary struct {
	Total        int `gorm:"column:total"`
	TextTotal    int `gorm:"column:text_total"`
	Participants int `gorm:"column:participants"`
}

type GroupChatWordCount struct {
	Text  string `gorm:"column:text"`
	Count int    `gorm:"column:count"`
}

type GroupChatUserCount struct {
	UserID   int64  `gorm:"column:user_id"`
	Nickname string `gorm:"column:nickname"`
	Count    int    `gorm:"column:count"`
}

// SaveGroupChatMessages inserts messages idempotently. History backfills and
// live events can overlap, so the (group_id, message_id) key ignores duplicates.
func SaveGroupChatMessages(rows []GroupChatMessage) error {
	if len(rows) == 0 {
		return nil
	}
	return DB.Clauses(clause.OnConflict{DoNothing: true}).CreateInBatches(rows, 200).Error
}

func SaveGroupChatMessage(row GroupChatMessage) error {
	return SaveGroupChatMessages([]GroupChatMessage{row})
}

// GetGroupChatMessages returns at most limit messages in chronological order.
// userID=0 includes the whole group.
func GetGroupChatMessages(groupID, userID int64, start, end time.Time, limit int) ([]GroupChatMessage, error) {
	if limit <= 0 || limit > 20_000 {
		limit = 20_000
	}
	query := DB.Where("group_id = ? AND created_at >= ? AND created_at < ?", groupID, start.Unix(), end.Unix())
	if userID != 0 {
		query = query.Where("user_id = ?", userID)
	}
	var rows []GroupChatMessage
	err := query.Order("created_at ASC, id ASC").Limit(limit).Find(&rows).Error
	return rows, err
}

func DeleteGroupChatMessagesBefore(cutoff time.Time) error {
	return DB.Where("created_at < ?", cutoff.Unix()).Delete(&GroupChatMessage{}).Error
}

func groupChatRange(groupID, userID int64, start, end time.Time) *gorm.DB {
	query := DB.Model(&GroupChatMessage{}).
		Where("group_id = ? AND created_at >= ? AND created_at < ? AND stat_excluded = false", groupID, start.Unix(), end.Unix())
	if userID != 0 {
		query = query.Where("user_id = ?", userID)
	}
	return query
}

func GetGroupChatSummary(groupID, userID int64, start, end time.Time) (GroupChatSummary, error) {
	var summary GroupChatSummary
	err := groupChatRange(groupID, userID, start, end).
		Select(`COUNT(*) AS total,
			COUNT(*) FILTER (WHERE btrim(content) <> '') AS text_total,
			COUNT(DISTINCT user_id) AS participants`).
		Scan(&summary).Error
	return summary, err
}

// GetGroupChatTopWords counts one occurrence per message. search_vector is
// generated by PostgreSQL with zhparser, so no message text is segmented in Go.
func GetGroupChatTopWords(groupID, userID int64, start, end time.Time, limit int) ([]GroupChatWordCount, error) {
	if limit <= 0 || limit > 512 {
		limit = 256
	}
	var rows []GroupChatWordCount
	query := `
		SELECT lexeme AS text, COUNT(*)::integer AS count
		FROM group_chat_messages AS message
		CROSS JOIN LATERAL unnest(tsvector_to_array(message.search_vector)) AS lexeme
		WHERE message.group_id = ?
		  AND message.created_at >= ? AND message.created_at < ?
		  AND message.stat_excluded = false
		  AND char_length(lexeme) >= 2`
	args := []any{groupID, start.Unix(), end.Unix()}
	if userID != 0 {
		query += " AND message.user_id = ?"
		args = append(args, userID)
	}
	query += `
		GROUP BY lexeme
		ORDER BY count DESC, char_length(lexeme) DESC, lexeme ASC
		LIMIT ?`
	args = append(args, limit)
	err := DB.Raw(query, args...).Scan(&rows).Error
	return rows, err
}

func GetGroupChatUserCounts(groupID int64, start, end time.Time, limit int) ([]GroupChatUserCount, error) {
	if limit <= 0 || limit > 100 {
		limit = 10
	}
	var rows []GroupChatUserCount
	err := DB.Raw(`
		SELECT user_id,
		       COALESCE((array_remove(array_agg(NULLIF(nickname, '') ORDER BY created_at DESC, id DESC), NULL))[1], '') AS nickname,
		       COUNT(*)::integer AS count
		FROM group_chat_messages
		WHERE group_id = ? AND created_at >= ? AND created_at < ? AND stat_excluded = false
		GROUP BY user_id
		ORDER BY count DESC, user_id ASC
		LIMIT ?`, groupID, start.Unix(), end.Unix(), limit).Scan(&rows).Error
	return rows, err
}

func FindGroupChatUsersSaying(groupID int64, start, end time.Time, keyword string, limit int) ([]GroupChatUserCount, error) {
	if limit <= 0 || limit > 100 {
		limit = 8
	}
	pattern := "%" + escapeLike(keyword) + "%"
	var rows []GroupChatUserCount
	err := DB.Raw(`
		SELECT user_id,
		       COALESCE((array_remove(array_agg(NULLIF(nickname, '') ORDER BY created_at DESC, id DESC), NULL))[1], '') AS nickname,
		       COUNT(*)::integer AS count
		FROM group_chat_messages
		WHERE group_id = ? AND created_at >= ? AND created_at < ?
		  AND stat_excluded = false AND content ILIKE ? ESCAPE '\'
		GROUP BY user_id
		ORDER BY count DESC, user_id ASC
		LIMIT ?`, groupID, start.Unix(), end.Unix(), pattern, limit).Scan(&rows).Error
	return rows, err
}

func GetLatestGroupChatNickname(groupID, userID int64, start, end time.Time) (string, error) {
	var nickname string
	err := groupChatRange(groupID, userID, start, end).
		Where("nickname <> ''").Order("created_at DESC, id DESC").Limit(1).
		Pluck("nickname", &nickname).Error
	return nickname, err
}

func escapeLike(value string) string {
	replacer := strings.NewReplacer(`\`, `\\`, `%`, `\%`, `_`, `\_`)
	return replacer.Replace(value)
}
